# Generated by Django 3.1.2 on 2023-06-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230531_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
