# Generated by Django 3.1.2 on 2023-06-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230605_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
